// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ6GOmg6c5Giw0MB5bbiYRLyFfX38QRCA',
    appId: '1:255708088105:web:8a7a1be5cdd051bfd11938',
    messagingSenderId: '255708088105',
    projectId: 'evently-app-95535',
    authDomain: 'evently-app-95535.firebaseapp.com',
    storageBucket: 'evently-app-95535.firebasestorage.app',
    measurementId: 'G-BNV4C1R0VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwkQ-X6DbExvQrTcVqf4jrTPf3KM_9jmU',
    appId: '1:255708088105:android:743564b78d80aaa3d11938',
    messagingSenderId: '255708088105',
    projectId: 'evently-app-95535',
    storageBucket: 'evently-app-95535.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLCxNsly01S2czqrfVQVrm0A3D95DgEs0',
    appId: '1:255708088105:ios:09b2ca00dd19179fd11938',
    messagingSenderId: '255708088105',
    projectId: 'evently-app-95535',
    storageBucket: 'evently-app-95535.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLCxNsly01S2czqrfVQVrm0A3D95DgEs0',
    appId: '1:255708088105:ios:09b2ca00dd19179fd11938',
    messagingSenderId: '255708088105',
    projectId: 'evently-app-95535',
    storageBucket: 'evently-app-95535.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ6GOmg6c5Giw0MB5bbiYRLyFfX38QRCA',
    appId: '1:255708088105:web:22e22be159b8edcdd11938',
    messagingSenderId: '255708088105',
    projectId: 'evently-app-95535',
    authDomain: 'evently-app-95535.firebaseapp.com',
    storageBucket: 'evently-app-95535.firebasestorage.app',
    measurementId: 'G-WWBX27L18G',
  );
}
